apiVersion: v1
kind: Service
metadata:
  name: shifman-backend-service
  namespace: ecom
  labels:
    app: shifman-backend
spec:
  selector:
    app: shifman-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31291
  type: NodePort
